version: 2

jobs:
   "Ubuntu": 
     # Ubuntu 18
     docker:
       - image: ubuntu:18.04
     steps:
       - checkout
       - run: |
          apt-get -q update -y
          apt-get -q install -y libedit-dev zlib1g-dev m4 build-essential
          mkdir install
          export VLSI_TOOLS_SRC=`pwd`
          export ACT_HOME=$VLSI_TOOLS_SRC/install
          ./configure $ACT_HOME || :

workflows:
   version: 2
   build:
     jobs: 
        - "Ubuntu"
          
